declare module 'vite-plugin-compression'
declare module 'vite-plugin-zip'
declare module 'highlight.js/lib/core'
declare module 'highlight.js/lib/languages/javascript'
declare module '@highlightjs/vue-plugin'
